language: node_js
node_js:
  - "0.10"
  - 4.2
  - stable
before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
env:
  - ORIENTDB_VERSION=2.0.14
  - ORIENTDB_VERSION=2.1.0
  - ORIENTDB_VERSION=2.1.3
  - ORIENTDB_VERSION=2.1.4-SNAPSHOT
