language: node_js
node_js:
  - "0.10"
before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
env:
  - ORIENTDB_VERSION=2.0.16
  - ORIENTDB_VERSION=2.0.17
  - ORIENTDB_VERSION=2.1.8
  - ORIENTDB_VERSION=2.1.9
